language: python
python:
- '3.6'
services:
- docker
before_install:
- make build-latest
- make build-test
- make run-test
- pip install -r tests/requirements.txt
script:
- make tests
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
- provider: script
  script: make push-latest
  on:
    branch: master
env:
  global:
  - secure: OcN8IHkmOPs9UhgyPorbgCiXP2Xj0e/YCbCd+FqSHmJUKEc28FWJ6nMrsR2L7nsNZ5FiyFszD2Cy3Ql+t4PXgBI1/1w42/k8cAy/4Wq738cjcMSH2Rm9ZxkwZHFJjyxxd105rn8F/fj40I5Smu8laR67upNL5S6qhQLWN+KDnoLWdrkIAG8JWVWsjXC9mEiW942WiXsGCIzhocV+iQqxz/uYekxc1xVMaBlX3p7Vr/QAnVpYUxQcfghNad9eIDz7Mubxdk+RbUtMbQJdG81bQssY4l0Pho4K6WO+kl89aOz8Y4dsIQWzB7tTQ/GE288Z+aIKWhde7RQYFYSFM9Jzf0GPDH+4MQPlDmeg6asGKgd9r7VWHJ3BCMlxUU1Bi+C1DvNmtvIXWjWRGLNGQtYs5ShJR6aEHWrW3nONCmXwR5cLcwiK2JwY1U/iYIGtkzapM+OVoayw64iAX3a7wpjF6ZN2IRSElCo0yewc4xpR7kt/3zQZNnPgc6lddzZeaqnse5/vWZe8fPKzBXnpOAgTcA26NQD5xunLJg/mKmdQQaPOcXukxgsxM95f/Ym6XCqC6WdK1LjX8fp2NcUNSqSnWJbA1vERtPOsj76YsmRJmkhTsAAye722ztJAovAC+lAH7aZqZfBMgvZv54Bdth3sTv806PVXnQy36O3OO3BYhVY=
  - secure: vjtFe5SXBD1ERxL9rzsVnVo/cjyNRORiMXEUZpocyBdQS8UfPGTdtFAPGaCKagxVDQeJWMBH6x+2CIz2YhrNhiyGD41lAxzEKem7gtHLBnLdPPDTAp51WcXJWv9MhPAvQYDiaj9SfGj2igyNFhUz1VKH2k+ci9z4QUJjtCVEx8YS/MX6Z690lf7bZ4ycnBb02dc9sRLhWqMyBTUubmX8SkGV2qxG1xbsI4umAdLPsC5IGEuxMdByCkxFt3n+csBC2wrzikoBMHjAaR9WgNcHUrTulB8WPKqzQSjXk7O9kd/kFQdY+TFI7tI/caex1XgSwyDesmEeEhckdS81H+oozz1d9/tJcamYWgCZ/P74+IP6nNsG0BDHf6xe/bH1RDSHptTU1f5GZJAu1M0got25bySDTsf7+IM8m/Z86T7YtMt1bFpaAyHiSQWt3UgCZoPB2Ob6Nz8DaZ+5y8QG/HGIJ/rcUIwgA9oORcT7YRgU1Ghd+AAOrgrYSDpPhX3L5mMxII7QEfuLRFJTY57mboLJfi6sjeRfwOczz3iHdk7beCz/quUCIb7Kb524UDUxZF1FsxXDKOse7Nv38dqyxwR4Rwq7Zi9gA7hLGEwi23mQOddV3whMA3N98bUtxYBAqrbvdhpI2gDFXouq2XMfHS+oI+rtI6XYk1YEMMfOQbO/zoA=
