language: python
version:
- '3.6'
services:
- docker
before_install:
- make build-latest
- make build-test
- make run-test
- pip install -r tests/requirements.txt
script:
- make tests
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
- provider: script
  script: make push-latest
  on:
    branch: master
env:
  global:
  - secure: J18RGncBYRzBFYDienRaf4nZRQN8h60O+mDQYAry1kh9DuqEdMpgw4tEjXRwIboFFgHcL293eD3UyhF+L4gobnPqLRNOXobhRyh3+0dGGjYXlI/kSYJahGe4noauM5GjXxhqI1CjfzZwLj6NGPxuKPyD/wN5sZKcv0P6zYwVsAm6ubXyCHHOG9g1gaD8voC4Loj2NnR1wjsHYsTWvRCjGHTRZwBTwXkNCemeEjLtSAB2zFVgRUM5b8xw4iEpMtrNvDpIp3ghIJT7UwEXmxXZrbt2+gTSESZUlyLSb5OnFP7gBIC5eWaJ68xmrsrP7sFo+GE7tyJwD22QrWAc1aCPNvW7bXV6oBqPCn/2aOzQDkbnLezDqDr7Q1el9dJzWK4l5gh8qNJjfTTvpr6xSlFgZJrsC8LFh0nv6P1glKGu1gIkyu3j6gX0cOhgpPt4BLX3dd16MYlJNviNTjRJOfzNjgFyd4vkUM9M4ZjzW+neSj5Q6or8XfqmS/Y/nmh7eTmuMIyze03dr1ScIjIeUQ9C0t1N2Cacr2sNe2H20kcAd3wOj86JpUtfRD9/gH8AFI3ihramPWxMs26zUK1FrRMwdTHUA5btOfoFCKj186fg0NEDsHDw4plHYIrHODkZOnPfU+r2kgXL+wCMnlFon7QYzHHU9s2Pp3T563BFTOTKZtE=
  - secure: xzTIo2WdUielUkbuw3mtx72JuTm+VwlM2CSYm7lh7riOryDl/dZpP14h8MMAPwOAagKyv6M574KZl2BH0sXbrynvX9Fu7s/gzV9Xznc9ubrQYsv5CWByZxbaXeQnMLV3o8whRbQQ6HRrF5ROTSex0LXOMWWI/3KBYFigqeoE6PmzWONK7Ihyb1Loa7gz5sFtst/+KsJTRN0QC/Z9W2mTeTrXzOaGnuWk99eru4Sfdpm6PkMVyRnblCqRSA9/naQnAQEvUJAnTAU7+y5dk5ycD9M6OghydoNJogkUOYO27OQ6oz6zllEofPYh+xg57swSALBmrkXlE7jfqa2O9PHPpasHf3KtAfcS7Y5jaHhAQCW4lcHx88M4lTlqUm69KatW7TzaaQFtIMibgoxpJJUGralt1GaXaV1CUSULNfvfy2thLgBWbZKje/undy47TbFX2gel7WkNGZZwiwh8u8s4tbPARo85wirqpEOwW4OCbYSgy0Cye9qXiv75ycoCBVc8rRNH6zwmoX2QReum20FPqTkkNOMy8uHodJ4EuWTkY6DyWl2JA7eZgqXR2DFmQCedWpQeUOuwr/Wt94HHE/TI4A6b1Ay4aN+oMN1qCWcFgr4PkKiOINI09Fmz0e/TD1iQLD9G4mDOS425m23HiJnTf16vuyaR0EtKu4g0zAKgmLs=
